create table "public"."comment_attachments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "comment" bigint not null,
    "file_path" text not null
);


alter table "public"."comment_attachments" enable row level security;

CREATE UNIQUE INDEX comment_attachments_pkey ON public.comment_attachments USING btree (id);

alter table "public"."comment_attachments" add constraint "comment_attachments_pkey" PRIMARY KEY using index "comment_attachments_pkey";

alter table "public"."comment_attachments" add constraint "public_comment_attachments_comment_fkey" FOREIGN KEY (comment) REFERENCES comments(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."comment_attachments" validate constraint "public_comment_attachments_comment_fkey";

grant delete on table "public"."comment_attachments" to "anon";

grant insert on table "public"."comment_attachments" to "anon";

grant references on table "public"."comment_attachments" to "anon";

grant select on table "public"."comment_attachments" to "anon";

grant trigger on table "public"."comment_attachments" to "anon";

grant truncate on table "public"."comment_attachments" to "anon";

grant update on table "public"."comment_attachments" to "anon";

grant delete on table "public"."comment_attachments" to "authenticated";

grant insert on table "public"."comment_attachments" to "authenticated";

grant references on table "public"."comment_attachments" to "authenticated";

grant select on table "public"."comment_attachments" to "authenticated";

grant trigger on table "public"."comment_attachments" to "authenticated";

grant truncate on table "public"."comment_attachments" to "authenticated";

grant update on table "public"."comment_attachments" to "authenticated";

grant delete on table "public"."comment_attachments" to "service_role";

grant insert on table "public"."comment_attachments" to "service_role";

grant references on table "public"."comment_attachments" to "service_role";

grant select on table "public"."comment_attachments" to "service_role";

grant trigger on table "public"."comment_attachments" to "service_role";

grant truncate on table "public"."comment_attachments" to "service_role";

grant update on table "public"."comment_attachments" to "service_role";


